server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Kill old cached Angular favicon
    location = /favicon.ico {
        return 204;
    }

    # Hashed assets — cache forever
    location ~* \.[0-9a-z]{8,}\.(js|css)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # index.html — never cache
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /swagger-ui/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
    }

    location /v3/api-docs/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
    }
}
