"""Add status field to StudyTopic model with default value

Revision ID: 0840737bf545
Revises: 131df4de504a
Create Date: 2024-11-08 08:20:52.684202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0840737bf545'
down_revision = '131df4de504a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_topics', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
