"""Add next_review to StudyTopic

Revision ID: 0aa481bcca99
Revises: 7e833234a504
Create Date: 2024-11-04 07:11:20.636584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa481bcca99'
down_revision = '7e833234a504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_review', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_topic', schema=None) as batch_op:
        batch_op.drop_column('next_review')

    # ### end Alembic commands ###
