"""Add review_count to LearningItem

Revision ID: 5ad7be204ff6
Revises: 1d03adc895e6
Create Date: 2024-10-29 06:43:42.064428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad7be204ff6'
down_revision = '1d03adc895e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_item', schema=None) as batch_op:
        batch_op.drop_column('review_count')

    # ### end Alembic commands ###
