"""Initial migration.

Revision ID: 1d03adc895e6
Revises: 
Create Date: 2024-10-28 08:01:21.788470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d03adc895e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_review', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_item', schema=None) as batch_op:
        batch_op.drop_column('next_review')

    # ### end Alembic commands ###
